### PR TITLE
re-organise and rename config options

### PR DESCRIPTION
**Pull request by chas-iot**
1. rename config options to use download and upload to replace transmit and receive
2. use `upload_min_percent` and `download_min_percent` instead of `transmit_kbits_min` and `receive_kbits_min`
3. add a section `advanced_settings` to the config file with the following options
 - `upload_delay_ms` and `download_delay_ms`  - The amount of delay (increase in RTT) that indicates bufferbloat. For high speed and relatively stable fiber connections, this can be reduced. For LTE and DOCIS/cable connections, the default should be correct. Was `max_delta_owd` in the lua code
 - `speed_hist_size` - The amount of "safe" speed history which the algorithm will maintain for reference during times of increased latency/congestion. Set too high, the algorithm will take days or weeks to stabilise. Set too low, the algorithm may not have enough good values to stabilise on.  Was `hist_size`
 - `high_load_level` - vary the detection of high load from 0.67 to 0.95
 - `reflector_type` - This is intended for future use and details are TBD.
4. update `sqm-autorate.lua` and `readme.MD` to follow the new config options
5. migrate users' old settings to new

### CODE REVIEW

**Comment by chas-iot** [comment]
Incorporates all feedback so far
I tested the migration on my settings

**Comment by moeller0** [comment]
Mmmh I am not sure that switching the minima from absolute (kbps) to relative percent. IMHO this will make two things harder:
a) comparing the realized minima in the log file with one's prediction/expectation
b) checking whether the selected minima are sane/not too small.

I would really like if such proposed changes would be discussed a bit more openly instead, maybe as part of the thread in the OpenWrt forum?

**Comment by moeller0** [comment]
speed_hist_size - The amount of "safe" speed history

How about calking that safe_speed_history_size_${unit} instead, replacing ${unit} with something apprpriate (count/N?)?

**Comment by moeller0** [comment]
Next proposal:
        option upload_kbits_base '10000'
         option download_kbits_base '10000'

coud we consider to:
a) move the unit to the very end, so upload_base_kbits?
b) change the unit,  from kbits to Kbps for Kilo bits per second, I always expnand kbits simply to the plural kilobits lacking the time component (but that is very subjective, point a) is my real point)

**Review by Fail-Safe — APPROVED** [review]

**Pull request merged**
