### PR TITLE
rename config options - for review

### PR DESCRIPTION
**Pull request by chas-iot**
1. Added a section `advanced_settings` to the config file with the following options
 - `speed_hist_size` - The amount of "safe" speed history which the algorithm will maintain for reference during times of increased latency/congestion. Set too high, the algorithm will take days or weeks to stabilise. Set too low, the algorithm may not have enough good values to stabilise on.  Was `hist_size`
 - `rtt_delta_bufferbloat`  - The amount of increase in RTT that indicates bufferbloat. For high speed and relatively stable fiber connections, this can be reduced. For LTE and DOCIS/cable connections, the default should be correct. Was `max_delta_owd`
 - `high_load_level` - vary the detection of high load from 0.67 to 0.95
 - `reflector_type` - This is intended for future use and details are TBD.
2. Updated `sqm-autorate.lua` and `readme.MD` to follow the new config options
3. Migration of users old settings to new

### CODE REVIEW

**Comment by moeller0** [comment]
rtt_delta_bufferbloat this is IMHO not the ideal change as it is factually wrong. OWD expads to one-way-delay, while RTT expands to round-trip-time, and:
RTT = OWD(up) + OWD(down)

Secondly, this value is not bufferbloat, but a threshold to classify delay excursions as potentially caused by bufferbloat.

How about something along the lines of:

max_OWD_threshold_ms
critical_OWD_threshold_ms
induced_OWD_threshold_ms
or if bufferloat needs to be in the name (not a fan of the term)
bufferbloat_OWD_threshold_ms

That is keep: the OWD, since RTT would be misleading; describe its function better by calling it threshold; and add the unit to the name so users get an idea what to fill in simply by looking at the config file.

Does that make any sense?


P.S.: I hope we actually split this up into individual parameters for the up and down directions.

**Comment by moeller0** [comment]
A different point, currently the config names and the variable names are quite different, could/should we actually homogenize them? Since this is not a widely distributed package yet, we are stil at liberty to make pretty wild rename actions (in the code anyway, but also in the config file). 
@chas-iot , @Fail-Safe , @Lochnair, @dlakelan what do you all think?

**Comment by Lochnair** [comment]
I agree with you @moeller0 that `rtt_delta_bufferbloat` would be misleading, and threshold would be better.
I kinda liked having delta in there though, made it clear that it doesn't include the baseline.

Also +1 to splitting it up into receive/transmit thresholds.

But yeah now's the time to go wild and make the breaking changes if we need to.

**Comment by moeller0** [comment]
Side note, on re-reading my comments seem awfully negative, this was not intended. I applaud the goal of improving the config file and documentation and really just want to propose something else for rtt_delta_bufferbloat.

**Comment by moeller0** [comment]
> I kinda liked having delta in there though, made it clear that it doesn't include the baseline.

Yes, I would be fine with dOWD or deltaOWD as part of the name, but things tend to get really long really fast, so I tried to be concise ;)

**Comment by moeller0** [comment]
Question: are transmit and receive really the best names in the config file? For normal users with sqm on the wan link would not up and down or in and out (in'n'out ;) ) not be more intuitive descriptors?

**Comment by Lochnair** [comment]
> Yes, I would be fine with dOWD or deltaOWD as part of the name, but things tend to get really long really fast, so I tried to be concise ;)
Fair enough, I'd rather leave it out than have the names become stupid long :D

> Question: are transmit and receive really the best names in the config file? For normal users with sqm on the wan link would not up and down or in and out (in'n'out ;) ) not be more intuitive descriptors?
They are already renamed is this PR actually if you look at the code, it's just not mentioned in the description

**Comment by chas-iot** [comment]
> 

I checked with collaborators and we are standardising on download and upload to replace transmit and receive.

When I get to it, I like the idea of ‘download_delay_trigger’ and ‘upload_delay_trigger’ to be the replacement for ‘delta_delay_trigger’ and previously ‘max_delta_owd’. But I am a complete novice (learning I hope) so will defer to the more knowledgable.

**Comment by moeller0** [comment]
> I checked with collaborators and we are standardising on download and upload to replace transmit and receive.

        Great. that mostly affects the config file and will match reasonably well with the ul_ dl_ and up down prefixes used in the code. I can also live with full download upload prefixes/IDs in the code, but I am just a bystander here so this is for the project owners/main developers to decide.

> 
> When I get to it, I like the idea of ‘download_delay_trigger’ and ‘upload_delay_trigger’ to be the replacement for ‘rtt_delta_bufferbloat’, ‘delta_delay_trigger’ and in the actual code ‘max_delta_owd’. But I am a complete novice (learning I hope) so will defer to the more knowledgable.

Whether it is called delay or OWD I do not care too much about (calling it delay would more naturally allow a mode in which RTTS instead of OWDs are measured, but even in that case splitting by direction makes sense, on my link with saturating loads and no sqm I see almost twice as much induced delay for upstream than for downstream loads).

I respectfully think that the value is not a trigger, but the threshold used to figure out whether a recent OWD (potentially also considering the current load) is large enough to trigger a rate-control intervention. And I "strongly" (see above why my strongly does not really matter) would like to see unit suffixes so config variables explain themselves as much as possible.

**Comment by chas-iot** [comment]
I agree on putting the units in the name, thank-you for reminding me. 
I defer to others on the better naming. Anyway, there’s a bit to do before I can get to that. Plus this interruption named work 🤣

**Comment by chas-iot** [comment]
This PR has become a little unwieldy, with 8 commits and the documentation out of line with the code. What I am considering is to create a new branch to consolidate and re-document all  the progress so far.
I do want to incorporate all the config changes into one update, as the shell code to perform the migration is intrusive and somewhat error-prone.
Any thoughts or suggestions?

**Comment by chas-iot** [comment]
Replaced by https://github.com/Fail-Safe/sqm-autorate/pull/67

**Pull request closed without merging**
